// Class automatically generated by Dev-C++ New Class wizard

#ifndef MODETABLE_H
#define MODETABLE_H

class ModeTable
{
    public:
        ModeTable();
        int search(char*);
        void indication(char*);
        void indication_2(char*);
        void indication_4(char*);
  		void show();
		void base2(char);
		char* base16(char *,int N);
        char* getopcode(){return op;};
		char* getind(){return ind;};
		char* getdisp(){return disp;};

		
    private:
        Addressing table[59];
        Register regtable[9];
        char re[9];
		char base2buff[5];
		char ind[7];
		char op[9];
		char disp[13];
		char hexbuff[9];
		char addr[20];
};
#endif // MODETABLE_H

