// Class automatically generated by Dev-C++ New Class wizard
#include <cstring>
using namespace std;
#include "register.h" // class's header file


// class constructor
void Register::SetValue(char *buff1,char *buff2)
{
    strcpy(Mnem,buff1);
    strcpy(num,buff2);
}



