// Class automatically generated by Dev-C++ New Class wizard
		// No description
		

#ifndef REGISTER_H
#define REGISTER_H

// No description
class Register
{
	public:		
		void SetValue(char*,char*);
		char* GetMnem(){return Mnem;};
		char* Getnum(){return num;};
	private:
	    char Mnem[3];
	    char num[3];
};

#endif // REGISTER_H

