/* Generated by Together */
import java.util.*;
public class Timer {
    public Timer() {
        start=System.currentTimeMillis();
    }

    public void restart() {
        start=System.currentTimeMillis();
    }

    public double elapsed() {
        end=System.currentTimeMillis();
        return (end-start)/1000.0;
    }

    private long start;
    private long end;
}
