/* Generated by Together */
import javax.swing.*;
import javax.swing.event.*;
import java.awt.*;
import java.awt.event.*;
import java.util.*;


public class Dataarray extends JFrame {
	Dataarray(){
		super("通 訊 錄");
        datalist=new LinkedList();


        Container container = getContentPane();
        container.setLayout(new FlowLayout());

		InsertButton=new JButton("新增");
        ChangeButton=new JButton("修改");
        SearchButton=new JButton("搜尋");
        DeleteButton=new JButton("刪除");

		container.add(InsertButton);
        container.add(ChangeButton);
        container.add(SearchButton);
        container.add(DeleteButton);

        ButtonHandler handler= new ButtonHandler();
        InsertButton.addActionListener(handler);
        DeleteButton.addActionListener(handler);
        ChangeButton.addActionListener(handler);
        SearchButton.addActionListener(handler);

        setSize(400,100);
        setLocation(400, 200);
        setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );
        setVisible(true);

        output="";
    }




    public static void main(String[] args) {
		Dataarray demo=new Dataarray();


	}

    private class ButtonHandler implements ActionListener {
	public void actionPerformed(ActionEvent e) {

		if(e.getSource()==InsertButton)
            Insertion();
        if(e.getSource()==ChangeButton)
			SetData();
        if(e.getSource()==SearchButton)
			Search();
        if(e.getSource()==DeleteButton)
			Deletion();

     }
    }



    public void Insertion() {

		num=JOptionPane.showInputDialog("學號");
        name=JOptionPane.showInputDialog("姓名");
        id=JOptionPane.showInputDialog("身份字號");
        tel=JOptionPane.showInputDialog("電話");


        datalist.add(num);
        datalist.add(name);
        datalist.add(id);
        datalist.add(tel);

	}

    public void Deletion() {
    }

    public void SetData() {
		String num,buff="搜尋失敗，沒有發現這個學號。";
        String[] temp=new String[3];
		num=JOptionPane.showInputDialog("學號");
		for(int i=0;i<datalist;i+=4)
        	if(datalist.get(i).)
            JOptionPane.showMessageDialog(null,buff);
    }

    public void Search() {
		String num,buff="搜尋失敗，沒有發現這個學號。";
		num=JOptionPane.showInputDialog("學號");
        JOptionPane.showMessageDialog(null,buff);
    }

    public void showoutput(){
		for(int i=0;i<datalist.size();i++){
            	output+=""+datalist.get(i)+" ";
			}output+="\n";
		JOptionPane.showMessageDialog(null,output);

	}
    private String name,num,id,tel,output;
   	private JButton InsertButton,DeleteButton,ChangeButton,SearchButton;
    private LinkedList datalist;
    private JTextArea Text;

}