// Class automatically generated by Dev-C++ New Class wizard

#ifndef HOP_COUNT_H
#define HOP_COUNT_H

#include <iomanip>
#include <set>
#include <queue>
#include <cmath>
using namespace std;
#include "deploy_map.h"
// No description
class hop_count
{
	public:
		// class constructor
		hop_count(class deploy_map *);
        void BFS(int,int);
        void Main_Method();
        int Broadcast_one_hop(int ***,int **);

        int Connect_componet(int ***,int **,int);
        void ReSet_component_id();
        class deploy_map* Get_hop_map();
		// class destructor
		~hop_count();
    private:
        class deploy_map *msc_map;
        int row,col;
        int ***component_id;
};

#endif // HOP_COUNT_H
