// Class automatically generated by Dev-C++ New Class wizard

#ifndef RELAY_NODE_H
#define RELAY_NODE_H

#include <set>
#include <queue>
#include <iostream>
using namespace std;

#include "deploy_map.h" // inheriting class's header file

// No description
class Relay_node
{
	public:
		// class constructor
		Relay_node(class deploy_map *);
        void Construct_adjacency_matrix();
        void BFS(int);
        int Find_node_id(int);
        void MST();
        void Connect_MST();
        bool deploy_edge(int,int);
        class deploy_map * Get_Map();
		// class destructor
		~Relay_node();
    private:
        class deploy_map *d_map;
        int row,col;
        int **length;
        int *node_id;
        set<string> edge_set;
};

#endif // RELAY_NODE_H
