// Class automatically generated by Dev-C++ New Class wizard

#ifndef SPIDER_H
#define SPIDER_H

#include <iomanip>
#include <set>
#include <algorithm>
#include <string>
#include <cmath>

#include "grid.h"
#include "deploy_map.h"
#include "neighbor_table.h"

typedef struct node_inf{
    int weight;
    int terminal_num;
    int m;
    double rm;
    int plus;
    double r_plus;
}node_inf;

typedef struct ratio{
    double r;
    int   id;
}ratio;
// No description
class spider
{
	public:
		// class constructor
		spider(int);
		// class destructor
		~spider();
		// No description
		void Embedded_to_Graph(class Grid *);
		// No description
		class deploy_map* Graph_to_Deploy();
		// No description
		void Construct_AP_distance();

        void search_path(int,int,int);
		// No description
		void Compute_ratio(int,int);
		// No description
		void Algorithm();
		// No description
		int Contract(int,int,int);
		// No description
		int Find_forest_path(set<string> &T,double rm,double r_plus);
		// No description
		int Contract_Forest(set<string> T,int terminal);

        int Get_v2_num(int id,int *);

    private:
        int row,col;
        int internal_weight;

        int **graph_adj;
        int graph_node_num,total_terminal;

        int **dist;
        int **back_track;

        node_inf *i_node;

        class Grid *map;

        double *terminal_dist;
        ratio  *term;
};

#endif // SPIDER_H
