// Class automatically generated by Dev-C++ New Class wizard

#ifndef MODETABLE_H
#define MODETABLE_H

class ModeTable
{
    public:
        ModeTable();
        int search(char*);
        void indication(char*);
  		void show();
		void base2(char);
		char* base16(char *);
        char* getopcode(){return op;};
		char* getind(){return ind;};
		char* getdisp(){return disp;};

		
    private:
        Addressing table[58];
		char base2buff[5];
		char ind[7];
		char op[9];
		char disp[13];
		char hexbuff[7];
};
#endif // MODETABLE_H

